apiVersion: v1
kind: Secret
metadata:
  name: user-management-mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "user"
  MYSQL_DATABASE: "urbanassist"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "user"