apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    app: mysql
<<<<<<< HEAD
  type: NodePort  # Use ClusterIP for internal access
=======
  type: NodePort  # to do change to the clusterIP in the production environment
>>>>>>> 4fd6dcf (Add MySQL service and secrets configuration for Kubernetes deployment)
