apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    app: mysql
  type: NodePort  # to do change to the clusterIP in the production environment
