apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
<<<<<<< HEAD
=======
  #values below are base64 encoded
  #echo -n 'password' | base64 -- command for encoding
>>>>>>> 4fd6dcf (Add MySQL service and secrets configuration for Kubernetes deployment)
  MYSQL_ROOT_PASSWORD: dmFpYmhhdg== # vaibhav - this is the password for the user with root privileges 
  MYSQL_USER: YWRtaW4= #admin
  MYSQL_PASSWORD: amFydmlzMDA3 #jarvis007
  MYSQL_DATABASE: ZGVtbw== #demo