server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: urbanassist
    password: UrbanAssist@2024!
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: my-secret-key-1234567890
