# k8s/user-auth/db/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-auth-mysql-pv-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi