# k8s/user-auth/db/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: user-auth-db-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "auth-root-pass123"
  MYSQL_DATABASE: "user_auth_db"
  MYSQL_USER: "auth_user"
  MYSQL_PASSWORD: "auth_user_pass123"