# k8s/user-auth/db/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-auth-mysql
spec:
  selector:
    app: user-auth-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306