server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urbanassist
    username: root

    password: root
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret: e7b03c0c0329ed5a8bbac042d38c6d93f7344516ac51203552476cf58f07b62c


