name: CI/CD Pipeline for User-Auth Microservice

on:
  push:
    paths:
      - 'user-auth/**'
  pull_request:
    paths:
      - 'user-auth/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your Java version
          distribution: 'temurin'

      - name: Build Java project with Maven
        run: mvn clean package -f user-auth/pom.xml # Replace with Gradle if needed

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-auth:latest -f user-auth/Dockerfile ./user-auth

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/user-auth:latest

  deploy:
    runs-on: self-hosted # Use self-hosted runner for deployment
    needs: build-and-push
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/user-auth:latest

      - name: Stop and remove existing container
        run: |
          docker stop user-auth || true
          docker rm user-auth || true

      - name: Run Docker container
        run: |
          docker run -d --name user-auth -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/user-auth:latest
