apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secrets
type: Opaque
stringData:
  PORT: "5051"
  CORS_ORIGIN: "*"
  RABIT_MQ_NAME: "deleteUser"
  RABIT_MQ_URL: "amqp://localhost"
  JWT_SECRET: "e7b03c0c0329ed5a8bbac042d38c6d93f7344516ac51203552476cf58f07b62c"
  DATABASE_NAME: "reviews"
  DATABASE_USER: "root"
  DATABASE_PASSWORD: "admin@vaibhav"
  DATABASE_HOST: "127.0.0.1"
